"""add user roles and active status

Revision ID: a087ca44dcc1
Revises: 9a738d9fec91
Create Date: 2026-10-01 02:34:07.329056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a087ca44dcc1'
down_revision: Union[str, Sequence[str], None] = '9a738d9fec91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=30), server_default='JOB_SEEKER', nullable=False))
    op.add_column('users', sa.Column('account_status', sa.String(length=20), server_default='ACTIVE', nullable=False))
    op.create_index(op.f('ix_users_account_status'), 'users', ['account_status'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_account_status'), table_name='users')
    op.drop_column('users', 'account_status')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
