"""add employer company relationship

Revision ID: bf37c0b3b0d2
Revises: a087ca44dcc1
Create Date: 2026-10-02 08:01:37.777672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf37c0b3b0d2'
down_revision: Union[str, Sequence[str], None] = 'a087ca44dcc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('employer_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_companies_employer_id'), 'companies', ['employer_id'], unique=True)
    op.create_foreign_key(None, 'companies', 'users', ['employer_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_index(op.f('ix_companies_employer_id'), table_name='companies')
    op.drop_column('companies', 'employer_id')
    # ### end Alembic commands ###
